// ============================================================
// js/auth/link_login.js — LINK-BASED LOGIN SYSTEM
// ============================================================

const LinkLogin = {
  /**
   * Generate a unique login link for an employee
   * @param {string} employeeId - The employee's ID
   * @returns {Promise<string>} The login URL
   */
  async generateLoginLink(employeeId) {
    try {
      // Generate unique token
      const token = crypto.randomUUID 
        ? crypto.randomUUID() 
        : 'tk_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8);
      
      // Calculate expiry: today at 9 PM
      const now = new Date();
      const expiry = new Date(now);
      expiry.setHours(21, 0, 0, 0); // 9 PM today
      
      // If current time is past 9 PM, set to tomorrow 9 PM
      if (now > expiry) {
        expiry.setDate(expiry.getDate() + 1);
      }
      
      // Create session object
      const session = {
        id: crypto.randomUUID ? crypto.randomUUID() : 'sess_' + Date.now(),
        employee_id: employeeId,
        token: token,
        created_at: now.toISOString(),
        expires_at: expiry.toISOString(),
        used: false,
        device_info: navigator.userAgent || 'Unknown'
      };
      
      // Save to IndexedDB
      await OctaneDB.dbPut('employee_sessions', session);
      
      // Push to Supabase (background)
      const client = typeof SupabaseOps !== 'undefined' ? SupabaseOps.getClient() : null;
      if (client) {
        try {
          await client.from('employee_sessions').insert([{
            id: session.id,
            employee_id: session.employee_id,
            token: session.token,
            created_at: session.created_at,
            expires_at: session.expires_at,
            used: session.used,
            device_info: session.device_info
          }]);
        } catch (e) {
          console.warn('Could not push session to Supabase:', e);
          // Queue for later sync
          if (window.syncQueue) {
            window.syncQueue.enqueue('PUSH_SESSION', session);
          }
        }
      }
      
      // Generate the full URL
      const baseUrl = window.location.origin + window.location.pathname;
      const loginUrl = baseUrl + '?login=' + token;
      
      // Copy to clipboard
      try {
        await navigator.clipboard.writeText(loginUrl);
      } catch (e) {
        console.warn('Could not copy to clipboard:', e);
      }
      
      return loginUrl;
      
    } catch (error) {
      console.error('Error generating login link:', error);
      throw error;
    }
  },

  /**
   * Validate token and log in employee
   * @param {string} token - The login token from URL
   * @returns {Promise<boolean>} Success or failure
   */
  async validateAndLogin(token) {
    try {
      // First, try to fetch the session from Supabase (to ensure it's fresh and generated by owner)
      let session = null;
      const client = typeof SupabaseOps !== 'undefined' ? SupabaseOps.getClient() : null;
      
      if (navigator.onLine && client) {
        const { data, error } = await client.from('employee_sessions').select('*').eq('token', token).single();
        if (!error && data) {
          session = data;
          await OctaneDB.dbPut('employee_sessions', session); // Cache locally
        }
      }
      
      // Fallback to IndexedDB if offline or Supabase fetch failed
      if (!session) {
        const allSessions = await OctaneDB.dbGetAll('employee_sessions');
        session = allSessions.find(s => s.token === token);
      }
      
      if (!session) {
        showNotification('Invalid login link. Please contact the owner.', 'danger');
        return false;
      }
      
      // Check if already used
      if (session.used) {
        showNotification('This link has already been used. Please request a new one.', 'danger');
        return false;
      }
      
      // Check if expired
      const now = new Date();
      const expiresAt = new Date(session.expires_at);
      if (now > expiresAt) {
        showNotification('This link has expired (valid only until 9 PM). Please request a new one.', 'danger');
        return false;
      }
      
      // Mark session as used
      session.used = true;
      session.used_at = now.toISOString();
      await OctaneDB.dbPut('employee_sessions', session);
      
      // Update in Supabase
      if (client && navigator.onLine) {
        try {
          await client
            .from('employee_sessions')
            .update({ used: true, used_at: now.toISOString() })
            .eq('id', session.id);
        } catch (e) {
          console.warn('Could not update session in Supabase:', e);
          if (window.syncQueue) window.syncQueue.enqueue('UPDATE_SESSION', session);
        }
      }
      
      // Get employee details
      let employee = await OctaneDB.dbGet('employees', session.employee_id);
      
      // If employee not found locally, try fetching from Supabase
      if (!employee && client && navigator.onLine) {
        const { data } = await client.from('employees').select('*').eq('id', session.employee_id).single();
        if (data) {
          employee = data;
          await OctaneDB.dbPut('employees', employee);
        }
      }
      
      if (!employee) {
        showNotification('Employee not found. Please contact the owner.', 'danger');
        return false;
      }
      
      // Log the employee in
      const userObj = {
        username: employee.phone,
        displayName: employee.name,
        role: employee.role || 'employee',
        id: employee.id
      };
      
      Auth.setSession(userObj, token);
      
      // Trigger UI update
      await Auth.checkAuth();
      showNotification(`✅ Welcome ${employee.name}!`, 'success');
      
      // Remove token from URL (clean URL)
      if (window.history && window.history.replaceState) {
        window.history.replaceState({}, document.title, window.location.pathname);
      }
      
      return true;
      
    } catch (error) {
      console.error('Error validating login:', error);
      showNotification('Login failed. Please try again.', 'danger');
      return false;
    }
  },

  /**
   * Check if there's a login token in the URL
   * @returns {Promise<boolean>} True if auto-login was attempted
   */
  async handleAutoLogin() {
    const urlParams = new URLSearchParams(window.location.search);
    const token = urlParams.get('login');
    
    if (token) {
      // Show loading state
      showNotification('🔐 Validating login link...', 'info');
      return await this.validateAndLogin(token);
    }
    
    return false;
  },

  /**
   * Clean up expired sessions (run daily)
   * @returns {Promise<number>} Number of sessions cleaned
   */
  async cleanupExpiredSessions() {
    try {
      const allSessions = await OctaneDB.dbGetAll('employee_sessions');
      const now = new Date();
      let count = 0;
      
      for (const session of allSessions) {
        const expiresAt = new Date(session.expires_at);
        if (now > expiresAt || session.used) {
          await OctaneDB.dbDelete('employee_sessions', session.id);
          count++;
        }
      }
      
      return count;
    } catch (e) {
      console.warn('Error cleaning sessions:', e);
      return 0;
    }
  }
};

window.LinkLogin = LinkLogin;
